name: meetified
description: AI-powered dating app with conversational profile building and intelligent matching

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_messaging: ^14.7.10
  firebase_analytics: ^10.7.4
  firebase_crashlytics: ^3.4.9
  firebase_storage: ^11.5.6
  
  # State Management
  provider: ^6.1.1
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9
  
  # HTTP & API
  http: ^1.1.2
  dio: ^5.4.0
  
  # Navigation
  go_router: ^13.2.0
  
  # UI & Design
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  lottie: ^2.7.0
  flutter_staggered_animations: ^1.1.1
  
  # Utilities
  intl: ^0.19.0
  uuid: ^4.2.1
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.2
  permission_handler: ^11.1.0
  device_info_plus: ^9.1.1
  package_info_plus: ^4.2.0
  
  # UI Components
  flutter_emoji: ^2.5.1
  emoji_picker_flutter: ^1.6.3
  image_picker: ^1.0.4
  
  # Payment
  upi_india: ^3.0.1
  razorpay_flutter: ^1.3.6
  
  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Animations
  flutter_animate: ^4.3.0
  
  # Location
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  
  # Utils
  logger: ^2.0.2+1
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  hive_generator: ^2.0.1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/fonts/
  
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700